In [27]:
import numpy as np

# Newtons method

In [28]:
def newtons(f, f_diff, x0, tol):
    x_n = x0
    print(f(x_n))
    print(f_diff(x_n))
    while np.abs(f(x_n)) > tol:
        x_n = x_n - (f(x_n)/f_diff(x_n))
        print(x_n)
    return x_n

In [29]:
f1 = lambda x: x**3 -2*x - 2
f1_diff = lambda x: 3*x**2 - 2
print(newtons(f1, f1_diff, 2, 1e-8))

2
10
1.8
1.7699481865284974
1.769292662905941
1.7692923542386998
1.7692923542386998


# Computer problem 2.1)

 **1)**

In [30]:
def naive_gauss(A):
    (n, m) = np.shape(A)  # matrix shape tuple (n rows, m columns)
    for j in range(n-1):  # for each row n
        for i in range(j + 1, n):  # for each pivot?
            multiplier = A[i][j]/A[j][j]
            for k in range(j, m):  # for each element from the pivot to end of row
                A[i][k] = A[i][k] - (A[j][k] * multiplier)
    return A

def back_substitution(AG):
    (n, m) = np.shape(AG)
    A = AG[:, :-1]
    b = AG[:, -1]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        for j in range(i+1, n):
            b[i] = b[i] - A[i][j]*x[j]
        x[i] = b[i]/A[i][i]
    return x
    
def hilbert(n):
    A = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            A[i][j] = 1.0/((i+1) + j)
    return A

In [31]:
# 1
A1 = np.array([
    [2, -2, -1, -2],
    [4, 1, -2, 1],
    [-2, 1, -1, -3]])
A2 = np.array([
    [1, 2, -1, 2],
    [0, 3, 1, 4],
    [2, -1, 1, 2]])
A3 = np.array([
    [2.0, 1, -4, -7],
    [1, -1, 1, -2],
    [-1, 3, -2, 6]])

print(back_substitution(naive_gauss(A1)))
print(back_substitution(naive_gauss(A2)))
print(back_substitution(naive_gauss(A3)))

[1. 1. 2.]
[1. 1. 1.]
[-1.  3.  2.]


**2)**

In [32]:
#2
H1 = hilbert(2)
H2 = hilbert(5)
H3 = hilbert(10)

H1_AG = np.hstack((H1, np.ones((2, 1))))
H2_AG = np.hstack((H2, np.ones((5, 1))))
H3_AG = np.hstack((H3, np.ones((10, 1))))

print(back_substitution(naive_gauss(H1_AG)))
print(back_substitution(naive_gauss(H2_AG)))
print(back_substitution(naive_gauss(H3_AG)))

[-2.  6.]
[    5.  -120.   630. -1120.   630.]
[-9.99736482e+00  9.89771861e+02 -2.37551338e+04  2.40195714e+05
 -1.26104860e+06  3.78319850e+06 -6.72576549e+06  7.00035724e+06
 -3.93773542e+06  9.23673408e+05]


# Computer problem 2.2)

**1) LU factorization**

In [33]:
def LU_factor(A):
    (n, m) = np.shape(A)  # matrix shape tuple (n rows, m columns)
    L = np.identity(n)
    for j in range(n-1):  # for each row n
        for i in range(j + 1, n):  # for each pivot?
            if A[j][j] == 0:
                return "Error"
            multiplier = A[i][j]/A[j][j]
            for k in range(j, m):  # for each element from the pivot to end of row
                A[i][k] = A[i][k] - (A[j][k] * multiplier)
            L[i][j] = multiplier
    return (L, A)


In [34]:
A1 = np.array([
    [3, 1, 2],
    [6, 3, 4],
    [3, 1, 5]])

A2 = np.array([
    [4, 2, 0],
    [4, 4, 2],
    [2, 2, 3]])

A3 = np.array([
    [1, -1, 1, 2],
    [0, 2, 1, 0],
    [1, 3, 4, 4],
    [0, 2, 1, -1]])

(L, U) = LU_factor(A2)
print(f"L:\n {L}")
print(f"U:\n {U}")

L:
 [[1.  0.  0. ]
 [1.  1.  0. ]
 [0.5 0.5 1. ]]
U:
 [[4 2 0]
 [0 2 2]
 [0 0 2]]


**2) Two-step back substitution**

In [35]:
def two_step_back_sub(L, U, b):
    (n, n) = L.shape
    c = np.zeros(n)
    x = np.zeros(n)

    # Lc = b --> Solve for c
    for i in range(n):
        for j in range(i):
            b[i] = b[i]-L[i][j]*c[j]
        c[i] = b[i]/L[i][i]
    
    # Ux = c --> Solve for x
    for i in range(n-1, -1, -1):
        for j in range(i+1, n):
            c[i] = c[i] - U[i][j]*x[j]
        x[i] = c[i]/U[i][i]

    return x

In [36]:
# 4a
A1 = np.array([
    [3, 1, 2], 
    [6, 3, 4],
    [3, 1, 5]])
b1 = np.array([[0, 1, 3]]).T

# 4b
A2 = np.array([
    [4, 2, 0], 
    [4, 4, 2],
    [2, 2, 3]])
b2 = np.array([[2, 4, 6]]).T


(L, U) = LU_factor(A1)
x = two_step_back_sub(L, U, b1)
print(two_step_back_sub(L, U, b1))

(L, U) = LU_factor(A2)
print(two_step_back_sub(L, U, b2))

[-1.  1.  1.]
[ 1. -1.  2.]


# Computer problem 2.3)

In [37]:
A1 = np.array([
    [10**-20, 1, 1],
    [1, 2, 4]])

A2 = np.array([
    [1, 2, 4],
    [10**-20, 1, 1]])

print(back_substitution(naive_gauss(A1)))
print(back_substitution(naive_gauss(A2)))

[0. 1.]
[2. 1.]


In [38]:
A = np.array([[-1, 0, 1], [2, 1, 1], [-1, 2, 0]])
print(LU_factor(A))

(array([[ 1.,  0.,  0.],
       [-2.,  1.,  0.],
       [ 1.,  2.,  1.]]), array([[-1,  0,  1],
       [ 0,  1,  3],
       [ 0,  0, -7]]))


# PA LU

In [39]:
import pprint
import scipy
import scipy.linalg   # SciPy Linear Algebra Library

A = np.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
P, L, U = scipy.linalg.lu(A)

print("P: ")
pprint.pprint(P)

print("A: ")
pprint.pprint(A)

print("L: ")
pprint.pprint(L)

print("U: ")
pprint.pprint(U)

P: 
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
A: 
array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])
L: 
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])
U: 
array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])
